<?php
### WEBSITE CURRENCY CONFIGURATION
$GLOBALS['CURRENCY'] = "&#8363;" ;

### TAX CONFIGURATION
$GLOBALS['TAX'] = 7.5 ;

### ADMINS IMAGE DIRECTORY
$GLOBALS['ADMINS_DIRECTORY'] = "public/uploads/admins/";

### CUSTOMER IMAGE DIRECTORY
$GLOBALS['CUSTOMER_DIRECTORY'] = "public/uploads/customer/";

### SLIDER IMAGE DIRECTORY
$GLOBALS['SLIDES_DIRECTORY'] = "public/uploads/slides/";

### PRODUCT MASTER IMAGE DIRECTORY
$GLOBALS['PRODUCT_DIRECTORY'] = "public/uploads/products/";

### ADDITIONAL PRODUCT IMAGE DIRECTORY
$GLOBALS['PRODUCTADD_DIRECTORY'] = "public/uploads/prodaddimages/";

### SUBCATEGORY BANNER IMAGE DIRECTORY
$GLOBALS['BANNER_DIRECTORY'] = "public/uploads/banners/";

### NO IMAGE
$GLOBALS['NO_IMAGE'] = "public/assets/imgs/no-image.png";
?>
